version: '3.8'

services:
  line-provider:
    image: line-provider
    build:
      context: ./line-provider
    ports:
      - "8080:8080"
    networks:
      - betting-network

  bet-maker:
    image: bet-maker
    build:
      context: ./bet-maker
    ports:
      - "8000:8000"
    networks:
      - betting-network

networks:
  betting-network:
    driver: bridge